using System.IO;
using System.Linq;
using System.Reflection;

namespace Chisel;

internal abstract class GraphWriter(TextWriter writer)
{
    public static GraphWriter Graphviz(TextWriter writer) => new GraphvizWriter(writer);

    public static GraphWriter Mermaid(TextWriter writer) => new MermaidWriter(writer);

    protected readonly TextWriter Writer = writer;

    public void Write(DependencyGraph graph, GraphOptions options)
    {
        var hasProject = graph.Packages.Any(e => e.IsProjectReference);
        var hasIgnored = graph.Packages.Any(e => e.State == PackageState.Ignore) && options.WriteIgnoredPackages;
        var hasRemoved = graph.Packages.Any(e => e.State == PackageState.Remove);
        WriteHeader(hasProject: hasProject, hasIgnored: hasIgnored, hasRemoved: hasRemoved, options);
        WriteEdges(graph, options);
        Writer.WriteLine();
        WriteNodes(graph, options);
        WriteFooter();
    }

    public abstract string FormatName { get; }
    protected abstract void WriteHeader(bool hasProject, bool hasIgnored, bool hasRemoved, GraphOptions options);
    protected abstract void WriteFooter();
    protected abstract void WriteRoot(Package package, GraphOptions options);
    protected abstract void WriteNode(Package package, GraphOptions options);
    protected abstract void WriteEdge(Package package, Package dependency, GraphOptions options);

    protected static string GetPackageId(Package package, GraphOptions options) => options.IncludeVersions ? $"{package.Name}/{package.Version}" : package.Name;

    protected static string GetGeneratedByComment()
    {
        var assembly = typeof(GraphWriter).Assembly;
        var repositoryUrl = assembly.GetCustomAttributes<AssemblyMetadataAttribute>().FirstOrDefault(e => e.Key == "RepositoryUrl")?.Value;
        return $"Generated by {repositoryUrl ?? assembly.GetName().Name}";
    }

    private static bool FilterIgnored(Package package, GraphOptions options) => options.WriteIgnoredPackages || package.State != PackageState.Ignore;

    private void WriteNodes(DependencyGraph graph, GraphOptions options)
    {
        foreach (var package in graph.Packages.Where(e => FilterIgnored(e, options)).OrderBy(e => e.Name))
        {
            WriteNode(package, options);
        }
    }

    private void WriteEdges(DependencyGraph graph, GraphOptions options)
    {
        foreach (var (package, dependencies) in graph.Dependencies.Select(e => (e.Key, e.Value)).Where(e => FilterIgnored(e.Key, options)).OrderBy(e => e.Key.Name))
        {
            if (dependencies.Count == 0)
            {
                WriteRoot(package, options);
            }
            foreach (var dependency in dependencies.Where(e => FilterIgnored(e, options)).OrderBy(e => e.Name))
            {
                WriteEdge(package, dependency, options);
            }
        }
    }
}